test:
    image: behodler/hardhat 
    tty: true
    command: test
    volumes:
        - ./:/app

build:
    image: behodler/hardhat 
    tty: true
    command: compile
    volumes:
        - ./:/app

install:
    image: node:14
    command: sh -c "yarn install"
    working_dir: /app
    volumes:
        - ./:/app