/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { LRNew, LRNewInterface } from "../LRNew";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "baseToken",
        type: "address",
      },
    ],
    name: "getPyroToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class LRNew__factory {
  static readonly abi = _abi;
  static createInterface(): LRNewInterface {
    return new utils.Interface(_abi) as LRNewInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): LRNew {
    return new Contract(address, _abi, signerOrProvider) as LRNew;
  }
}
