/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { LROld, LROldInterface } from "../LROld";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "baseToken",
        type: "address",
      },
    ],
    name: "baseTokenMapping",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class LROld__factory {
  static readonly abi = _abi;
  static createInterface(): LROldInterface {
    return new utils.Interface(_abi) as LROldInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): LROld {
    return new Contract(address, _abi, signerOrProvider) as LROld;
  }
}
