/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  SimpleLoanOfficer,
  SimpleLoanOfficerInterface,
} from "../SimpleLoanOfficer";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "pyroToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "borrower",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "baseTokenBorrowed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "pyroTokenStaked",
        type: "uint256",
      },
    ],
    name: "setObligationFor",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610308806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063f7e6588314610030575b600080fd5b61004a6004803603810190610045919061013a565b610060565b604051610057919061022a565b60405180910390f35b60008473ffffffffffffffffffffffffffffffffffffffff166362748c9b8585856040518463ffffffff1660e01b815260040161009f939291906101f3565b602060405180830381600087803b1580156100b957600080fd5b505af11580156100cd573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100f1919061019d565b9050949350505050565b60008135905061010a8161028d565b92915050565b60008151905061011f816102a4565b92915050565b600081359050610134816102bb565b92915050565b6000806000806080858703121561015057600080fd5b600061015e878288016100fb565b945050602061016f878288016100fb565b935050604061018087828801610125565b925050606061019187828801610125565b91505092959194509250565b6000602082840312156101af57600080fd5b60006101bd84828501610110565b91505092915050565b6101cf81610245565b82525050565b6101de81610257565b82525050565b6101ed81610283565b82525050565b600060608201905061020860008301866101c6565b61021560208301856101e4565b61022260408301846101e4565b949350505050565b600060208201905061023f60008301846101d5565b92915050565b600061025082610263565b9050919050565b60008115159050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000819050919050565b61029681610245565b81146102a157600080fd5b50565b6102ad81610257565b81146102b857600080fd5b50565b6102c481610283565b81146102cf57600080fd5b5056fea2646970667358221220255481d341e8a7d866a14d8d8c1d645c0c180b57c37a200e870834f0f123479564736f6c63430008040033";

export class SimpleLoanOfficer__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<SimpleLoanOfficer> {
    return super.deploy(overrides || {}) as Promise<SimpleLoanOfficer>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SimpleLoanOfficer {
    return super.attach(address) as SimpleLoanOfficer;
  }
  connect(signer: Signer): SimpleLoanOfficer__factory {
    return super.connect(signer) as SimpleLoanOfficer__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SimpleLoanOfficerInterface {
    return new utils.Interface(_abi) as SimpleLoanOfficerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SimpleLoanOfficer {
    return new Contract(address, _abi, signerOrProvider) as SimpleLoanOfficer;
  }
}
