/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface LachesisLikeInterface extends utils.Interface {
  functions: {
    "cut(address)": FunctionFragment;
    "measure(address,bool,bool)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "cut" | "measure"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "cut",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "measure",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<boolean>,
      PromiseOrValue<boolean>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "cut", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "measure", data: BytesLike): Result;

  events: {};
}

export interface LachesisLike extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LachesisLikeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cut(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean, boolean]>;

    measure(
      token: PromiseOrValue<string>,
      valid: PromiseOrValue<boolean>,
      burnable: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  cut(
    token: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<[boolean, boolean]>;

  measure(
    token: PromiseOrValue<string>,
    valid: PromiseOrValue<boolean>,
    burnable: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    cut(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean, boolean]>;

    measure(
      token: PromiseOrValue<string>,
      valid: PromiseOrValue<boolean>,
      burnable: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    cut(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    measure(
      token: PromiseOrValue<string>,
      valid: PromiseOrValue<boolean>,
      burnable: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    cut(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    measure(
      token: PromiseOrValue<string>,
      valid: PromiseOrValue<boolean>,
      burnable: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
