/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface SnufferCapInterface extends utils.Interface {
  functions: {
    "_liquidityReceiver()": FunctionFragment;
    "snuff(address,address,uint8)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "_liquidityReceiver" | "snuff"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_liquidityReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "snuff",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "_liquidityReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "snuff", data: BytesLike): Result;

  events: {};
}

export interface SnufferCap extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SnufferCapInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _liquidityReceiver(overrides?: CallOverrides): Promise<[string]>;

    snuff(
      pyroToken: PromiseOrValue<string>,
      targetContract: PromiseOrValue<string>,
      exempt: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  _liquidityReceiver(overrides?: CallOverrides): Promise<string>;

  snuff(
    pyroToken: PromiseOrValue<string>,
    targetContract: PromiseOrValue<string>,
    exempt: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    _liquidityReceiver(overrides?: CallOverrides): Promise<string>;

    snuff(
      pyroToken: PromiseOrValue<string>,
      targetContract: PromiseOrValue<string>,
      exempt: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    _liquidityReceiver(overrides?: CallOverrides): Promise<BigNumber>;

    snuff(
      pyroToken: PromiseOrValue<string>,
      targetContract: PromiseOrValue<string>,
      exempt: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _liquidityReceiver(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    snuff(
      pyroToken: PromiseOrValue<string>,
      targetContract: PromiseOrValue<string>,
      exempt: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
