/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface V2MigratorInterface extends ethers.utils.Interface {
  functions: {
    "LR_new()": FunctionFragment;
    "LR_old()": FunctionFragment;
    "migrate(address,address,string,string,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "LR_new", values?: undefined): string;
  encodeFunctionData(functionFragment: "LR_old", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "migrate",
    values: [string, string, string, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "LR_new", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "LR_old", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "migrate", data: BytesLike): Result;

  events: {};
}

export class V2Migrator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: V2MigratorInterface;

  functions: {
    LR_new(overrides?: CallOverrides): Promise<[string]>;

    LR_old(overrides?: CallOverrides): Promise<[string]>;

    migrate(
      ptoken2: string,
      ptoken3: string,
      nameNew: string,
      symbolNew: string,
      p2token_amount: BigNumberish,
      p3token_expectedAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  LR_new(overrides?: CallOverrides): Promise<string>;

  LR_old(overrides?: CallOverrides): Promise<string>;

  migrate(
    ptoken2: string,
    ptoken3: string,
    nameNew: string,
    symbolNew: string,
    p2token_amount: BigNumberish,
    p3token_expectedAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    LR_new(overrides?: CallOverrides): Promise<string>;

    LR_old(overrides?: CallOverrides): Promise<string>;

    migrate(
      ptoken2: string,
      ptoken3: string,
      nameNew: string,
      symbolNew: string,
      p2token_amount: BigNumberish,
      p3token_expectedAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    LR_new(overrides?: CallOverrides): Promise<BigNumber>;

    LR_old(overrides?: CallOverrides): Promise<BigNumber>;

    migrate(
      ptoken2: string,
      ptoken3: string,
      nameNew: string,
      symbolNew: string,
      p2token_amount: BigNumberish,
      p3token_expectedAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    LR_new(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    LR_old(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    migrate(
      ptoken2: string,
      ptoken3: string,
      nameNew: string,
      symbolNew: string,
      p2token_amount: BigNumberish,
      p3token_expectedAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
