/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface V2MigratorInterface extends utils.Interface {
  functions: {
    "LR_new()": FunctionFragment;
    "migrate(address,address,uint256,uint256)": FunctionFragment;
    "migrateMany(address[],address[],uint256[],uint256[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "LR_new" | "migrate" | "migrateMany"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "LR_new", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "migrate",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "migrateMany",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "LR_new", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "migrate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "migrateMany",
    data: BytesLike
  ): Result;

  events: {};
}

export interface V2Migrator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: V2MigratorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    LR_new(overrides?: CallOverrides): Promise<[string]>;

    migrate(
      ptoken2: PromiseOrValue<string>,
      ptoken3: PromiseOrValue<string>,
      p2token_amount: PromiseOrValue<BigNumberish>,
      p3token_expectedAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    migrateMany(
      ptoken2: PromiseOrValue<string>[],
      ptoken3: PromiseOrValue<string>[],
      p2token_amount: PromiseOrValue<BigNumberish>[],
      p3token_expectedAmount: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  LR_new(overrides?: CallOverrides): Promise<string>;

  migrate(
    ptoken2: PromiseOrValue<string>,
    ptoken3: PromiseOrValue<string>,
    p2token_amount: PromiseOrValue<BigNumberish>,
    p3token_expectedAmount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  migrateMany(
    ptoken2: PromiseOrValue<string>[],
    ptoken3: PromiseOrValue<string>[],
    p2token_amount: PromiseOrValue<BigNumberish>[],
    p3token_expectedAmount: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    LR_new(overrides?: CallOverrides): Promise<string>;

    migrate(
      ptoken2: PromiseOrValue<string>,
      ptoken3: PromiseOrValue<string>,
      p2token_amount: PromiseOrValue<BigNumberish>,
      p3token_expectedAmount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    migrateMany(
      ptoken2: PromiseOrValue<string>[],
      ptoken3: PromiseOrValue<string>[],
      p2token_amount: PromiseOrValue<BigNumberish>[],
      p3token_expectedAmount: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    LR_new(overrides?: CallOverrides): Promise<BigNumber>;

    migrate(
      ptoken2: PromiseOrValue<string>,
      ptoken3: PromiseOrValue<string>,
      p2token_amount: PromiseOrValue<BigNumberish>,
      p3token_expectedAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    migrateMany(
      ptoken2: PromiseOrValue<string>[],
      ptoken3: PromiseOrValue<string>[],
      p2token_amount: PromiseOrValue<BigNumberish>[],
      p3token_expectedAmount: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    LR_new(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    migrate(
      ptoken2: PromiseOrValue<string>,
      ptoken3: PromiseOrValue<string>,
      p2token_amount: PromiseOrValue<BigNumberish>,
      p3token_expectedAmount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    migrateMany(
      ptoken2: PromiseOrValue<string>[],
      ptoken3: PromiseOrValue<string>[],
      p2token_amount: PromiseOrValue<BigNumberish>[],
      p3token_expectedAmount: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
