/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BurnEYESnufferCap__factory } from "./BurnEYESnufferCap__factory";
export { Burnable__factory } from "./Burnable__factory";
