/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as baseTokenSol from "./BaseToken.sol";
export type { baseTokenSol };
export type { Lachesis } from "./Lachesis";
export type { PyroSender } from "./PyroSender";
export type { SimpleLoanOfficer } from "./SimpleLoanOfficer";
